import json

print("=" * 80)
print("MELHORIAS NO MATCHING - COMPARAÇÃO")
print("=" * 80)

print("\n📊 ANTES vs DEPOIS:")
print("-" * 80)
print(f"{'MÉTRICA':<40} {'ANTES':<15} {'DEPOIS':<15} {'MELHORIA'}")
print("-" * 80)
print(f"{'Total de matches':<40} {'344':<15} {'404':<15} {'+60 (+17.4%)'}")
print(f"{'Taxa de sucesso':<40} {'61.5%':<15} {'72.3%':<15} {'+10.8%'}")
print(f"{'Matches por dicionário':<40} {'334':<15} {'399':<15} {'+65'}")
print(f"{'Matches por similaridade':<40} {'10':<15} {'5':<15} {'-5'}")
print()
print(f"{'High FODMAP matches':<40} {'103':<15} {'119':<15} {'+16'}")
print(f"{'Low FODMAP matches':<40} {'217':<15} {'260':<15} {'+43'}")
print(f"{'Free FODMAP matches':<40} {'24':<15} {'25':<15} {'+1'}")

print("\n✅ EXPANSÕES REALIZADAS NO DICIONÁRIO:")
print("-" * 80)
print("1. Vegetais: De ~50 para ~100 termos")
print("   + Variações (broccoli/broccolini, pepper/bell pepper/capsicum)")
print("   + Ervas (parsley, basil, mint, cilantro, etc)")
print("   + Tipos específicos de feijão e leguminosas")
print()
print("2. Frutas: De ~30 para ~60 termos")
print("   + Frutas tropicais (dragon fruit, breadfruit, jackfruit)")
print("   + Variações (pawpaw/papaya, kiwi/kiwifruit)")
print("   + Frutas secas e cristalizadas")
print()
print("3. Carnes: De ~10 para ~35 termos")
print("   + Tipos de carne (veal, mutton, venison, wild boar)")
print("   + Aves (quail, duck, goose)")
print("   + Miúdos (liver, kidney, heart)")
print()
print("4. Peixes: De ~15 para ~55 termos")
print("   + Peixes específicos (sea bass, sea bream, monkfish)")
print("   + Mariscos (clams, cockles, scallops, whelks)")
print("   + Cefalópodes (octopus, squid, cuttlefish)")
print()
print("5. Laticínios: De ~15 para ~45 termos")
print("   + Tipos de queijo (gouda, emmental, gruyere, etc)")
print("   + Bebidas vegetais (almond, soy, oat, rice milk)")
print("   + Variações de iogurte e natas")
print()
print("6. Cereais: De ~15 para ~90 termos")
print("   + Tipos de pão (sourdough, rye, ciabatta, baguette)")
print("   + Massas (spaghetti, penne, lasagna, gnocchi)")
print("   + Tipos de arroz (basmati, wild, brown)")
print("   + Cereais diversos (quinoa, bulgur, millet)")
print()
print("7. Nozes e Sementes: De ~10 para ~25 termos")
print("   + Mais tipos de nozes (macadamia, brazil nut)")
print("   + Sementes (hemp, poppy, flax)")
print()
print("8. Condimentos: De ~15 para ~100+ termos")
print("   + Especiarias completas (turmeric, cumin, cardamom)")
print("   + Óleos diversos (coconut, sesame, canola)")
print("   + Molhos e temperos (worcestershire, fish sauce, tahini)")
print("   + Bebidas (coffee, tea, wine, beer, spirits)")

print("\n🎯 PALAVRAS-CHAVE ADICIONADAS:")
print("-" * 80)
print("Total de traduções no dicionário: ~350+ termos")
print("Cobertura aumentada de:")
print("  • Inglês britânico vs americano (courgette/zucchini, aubergine/eggplant)")
print("  • Singular e plural (bean/beans, tomato/tomatoes)")
print("  • Variações regionais (prawns/shrimp, biscuit/cookie)")
print("  • Termos compostos (brown rice, sweet potato, ice cream)")

print("\n💡 RESULTADO:")
print("-" * 80)
print(f"✓ Taxa de match aumentou de 61.5% para 72.3%")
print(f"✓ 60 novas equivalências encontradas")
print(f"✓ 404 alimentos FODMAP agora mapeados para tabela portuguesa")
print(f"✓ Cobertura de 72.3% dos alimentos FODMAP")

print("\n📁 ARQUIVO ATUALIZADO:")
print("-" * 80)
print("fodmap_portuguese_equivalences.json")
print(f"  • 404 equivalências completas")
print(f"  • Match score para cada par")
print(f"  • Tipo de match (dictionary/similarity)")
print(f"  • Notas de porção FODMAP")
print(f"  • Categorias de ambos os sistemas")

print("\n" + "=" * 80)
print("✓ DICIONÁRIO EXPANDIDO E OTIMIZADO COM SUCESSO!")
print("=" * 80)
